# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '15432:5432'

volumes:
  postgres: